-- MySQL Script generated by MySQL Workbench
-- Mon Mar  4 14:45:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_quitanda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_quitanda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_quitanda` DEFAULT CHARACTER SET utf8 ;
USE `db_quitanda` ;

-- -----------------------------------------------------
-- Table `db_quitanda`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_quitanda`.`tb_categorias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_quitanda`.`tb_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_quitanda`.`tb_clientes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `endereço` VARCHAR(255) NULL,
  `telefone` VARCHAR(15) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_quitanda`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_quitanda`.`tb_produtos` (
  `id` BIGINT NOT NULL,
  `nome` VARCHAR(80) NULL,
  `descrição` VARCHAR(250) NULL,
  `preço` DECIMAL(6,2) NULL,
  `unidade` VARCHAR(50) NULL,
  `categoria_id` BIGINT NULL,
  `clientes_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_produtos_tb_categorias_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_tb_produtos_tb_clientes1_idx` (`clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produtos_tb_categorias`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `db_quitanda`.`tb_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produtos_tb_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `db_quitanda`.`tb_clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
